language: java
jdk:
  - openjdk8

services:
  - postgresql

before_script:
  - psql -c "create database learning_spring;" -U postgres

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433
